server.port: 8888
spring:
  application:
    name: social-rating-application-config-server
  cloud:
    consul:
      enabled: true
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: "${spring.application.name}-${spring.cloud.client.hostname}-${random.int[1,999999]}"
        # Get only services that are passing the health check
        query-passing: true
        register: true
        deregister: true
        health-check-interval: 10s
        health-check-timeout: 10s
        health-check-critical-timeout: 10s
    config:
      server:
        git:
          uri: https://github.com/cloud-native-java-with-k8s-livelessons/configuration-config.git
          skipSslValidation: true
        default-label: main
  redis:
    database: 0
    host: localhost
    port: 6379
    password: Redis2019!
    timeout: 60000
logging:
  level:
    br:
      com:
        palerique: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true
    tags:
      application: "${spring.application.name}"
      instance: "${spring.cloud.consul.discovery.instance-id}"
    export:
      prometheus:
        enabled: true
        pushgateway:
          enabled: true
          base-url: localhost:9091
          shutdown-operation: push
          push-rate: 5s
