# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Grant execute permission for build script
        run: chmod +x build.sh
      - name: Grant execute permission for gradlew
        run: find . -name 'gradlew' -type f -prune -print -exec chmod +x {} \;
      - name: Build with Gradle
        run: ./build.sh
